# Generated by Django 5.1 on 2024-08-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_alter_video_released_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='released_at',
            field=models.DateTimeField(),
        ),
    ]
