# Generated by Django 5.1 on 2024-08-15 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_video_category_alter_video_released_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='released_at',
            field=models.DateTimeField(verbose_name=datetime.date(2024, 8, 15)),
        ),
    ]
