# Generated by Django 5.1 on 2024-08-15 13:09

import django.forms.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_alter_video_released_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='released_at',
            field=models.DateTimeField(verbose_name=django.forms.fields.DateTimeField),
        ),
    ]
